// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDjuLGe7wvKpB_3DSa7yarL2cu2XJiDvk',
    appId: '1:176654083227:web:58f46cc5f69026b3e0123e',
    messagingSenderId: '176654083227',
    projectId: 'pruebas-app-movil',
    authDomain: 'pruebas-app-movil.firebaseapp.com',
    storageBucket: 'pruebas-app-movil.appspot.com',
    measurementId: 'G-M1VBSV7CXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqGWDZMym0LucdtUYV74AvETEDhJqD5w',
    appId: '1:176654083227:android:48b2098b1feb3839e0123e',
    messagingSenderId: '176654083227',
    projectId: 'pruebas-app-movil',
    storageBucket: 'pruebas-app-movil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4yr4caGyQ6_L2v67rk-nGGrFTG62eeos',
    appId: '1:176654083227:ios:2b420cabf23f0bc7e0123e',
    messagingSenderId: '176654083227',
    projectId: 'pruebas-app-movil',
    storageBucket: 'pruebas-app-movil.appspot.com',
    androidClientId: '176654083227-agq7m0uf2qudnu5ohvmjslt65m2fd7nn.apps.googleusercontent.com',
    iosClientId: '176654083227-k90n146qsqonlkb7bkmvqns0pp3hmmrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.portalCorpV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4yr4caGyQ6_L2v67rk-nGGrFTG62eeos',
    appId: '1:176654083227:ios:2b420cabf23f0bc7e0123e',
    messagingSenderId: '176654083227',
    projectId: 'pruebas-app-movil',
    storageBucket: 'pruebas-app-movil.appspot.com',
    androidClientId: '176654083227-agq7m0uf2qudnu5ohvmjslt65m2fd7nn.apps.googleusercontent.com',
    iosClientId: '176654083227-k90n146qsqonlkb7bkmvqns0pp3hmmrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.portalCorpV2',
  );
}
